winget install Microsoft.VisualStudioCode
winget install Microsoft.VisualStudio.2022.Enterprise
winget install Microsoft.VisualStudio.2022.Enterprise-Preview
winget install Microsoft.Office
winget install Audacity.Audacity
winget install TechSmith.Camtasia
winget install Amazon.WorkspacesClient
winget install Microsoft.AzureDataStudio
winget install DBBrowserForSQLite.DBBrowserForSQLite
winget install Microsoft.Git
winget install GitHub.GitLFS
winget install GitHub.GitHubDesktopBeta
winget install Microsoft.PowerBI
winget install DaxStudio.DaxStudio
